spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    pool:
      enabled: true
    username: root
    password: root
    url: r2dbc:mysql://localhost:3306/r2dbc

server:
  port: 9999
logging:
  level:
    root: debug
    org.springramework.r2dbc.core: debug
